import assert from "node:assert/strict";
import { createRequire } from "node:module";
import test from "node:test";
import { createTemplateFiles, createTemplateSourceFiles, listTemplates, renderTemplateFiles, templateManifest, templatePackageVersion, templateProjectNameToken } from "./index.js";

const packageJson = createRequire(import.meta.url)("../package.json") as { version: string };

test("template manifest exposes package metadata", () => {
  assert.equal(templatePackageVersion, packageJson.version);
  assert.equal(templateManifest.name, "tsuz-template");
  assert.equal(templateManifest.schemaVersion, "0.5");
  assert.equal(templateManifest.version, packageJson.version);
  assert.deepEqual(templateManifest.changelog, [
    "Add manifest v0.5 metadata for template discovery.",
    "Add private template repository workflow documentation."
  ]);
  assert.deepEqual(
    templateManifest.templates.map((template) => template.name),
    ["default", "monorepo", "vue3", "mfe", "mfe-main", "mfe-app", "react", "python-main", "python-app"]
  );
  assert.deepEqual(templateManifest.templates.find((template) => template.name === "vue3"), {
    name: "vue3",
    title: "Vue 3 Web App",
    description: "Vue 3 app with Vite, Router, Pinia, ESLint, Docker, and CI",
    tags: ["vue", "vite", "spa", "docker"],
    recommendedFor: ["admin", "dashboard", "web app"],
    node: ">=20",
    packageManagers: ["pnpm"],
    nextSteps: ["pnpm install", "pnpm dev"]
  });
});

test("listTemplates returns available templates", () => {
  assert.deepEqual(listTemplates(), ["default", "monorepo", "vue3", "mfe", "mfe-main", "mfe-app", "react", "python-main", "python-app"]);
});

function assertMfeCiWorkflow(content: string) {
  assert.match(content, /name: CI/);
  assert.match(content, /pull_request/);
  assert.match(content, /push/);
  assert.match(content, /main/);
  assert.match(content, /master/);
  assert.match(content, /actions\/checkout@v4/);
  assert.match(content, /pnpm\/action-setup@v4/);
  assert.match(content, /version: 8\.15\.9/);
  assert.match(content, /actions\/setup-node@v4/);
  assert.match(content, /node-version: 20/);
  assert.match(content, /cache: pnpm/);
  assert.match(content, /pnpm install --frozen-lockfile/);
  assert.match(content, /pnpm lint/);
  assert.match(content, /pnpm format:check/);
  assert.match(content, /pnpm test/);
  assert.match(content, /pnpm build/);
  assert.match(content, /pnpm exec playwright install --with-deps chromium/);
  assert.match(content, /pnpm test:e2e/);
}

function assertMfeDeployWorkflow(content: string) {
  assert.match(content, /name: Deploy/);
  assert.match(content, /test-v\*\.\*\.\*/);
  assert.match(content, /product-v\*\.\*\.\*/);
  assert.match(content, /workflow_dispatch/);
  assert.match(content, /environment/);
  assert.match(content, /image_tag/);
  assert.match(content, /version/);
  assert.match(content, /should_build/);
  assert.match(content, /permissions:/);
  assert.match(content, /packages: write/);
  assert.match(content, /docker build/);
  assert.match(content, /docker push/);
  assert.match(content, /DOCKER_REGISTRY_TOKEN/);
  assert.match(content, /SSH_PRIVATE_KEY/);
  assert.match(content, /VITE_API_BASE_URL/);
  assert.match(content, /VITE_MFE_APP_ENTRY/);
  assert.match(content, /VITE_APP_ENV/);
  assert.match(content, /docker-compose\.yml/);
  assert.match(content, /scp/);
  assert.match(content, /ssh/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.yml pull app/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.yml up -d --no-build app/);
  assert.match(content, /Refusing to deploy a latest tag/);
}

function assertPythonDeployWorkflow(content: string, includePrivateKey: boolean) {
  assert.match(content, /name: Deploy/);
  assert.match(content, /test-v\*\.\*\.\*/);
  assert.match(content, /product-v\*\.\*\.\*/);
  assert.match(content, /workflow_dispatch/);
  assert.match(content, /environment/);
  assert.match(content, /image_tag/);
  assert.match(content, /version/);
  assert.match(content, /should_build/);
  assert.match(content, /permissions:/);
  assert.match(content, /packages: write/);
  assert.match(content, /docker build/);
  assert.match(content, /docker push/);
  assert.match(content, /DOCKER_REGISTRY_TOKEN/);
  assert.match(content, /SSH_PRIVATE_KEY/);
  assert.match(content, /DATABASE_URL/);
  assert.match(content, /REDIS_URL/);
  assert.match(content, /JWT_PUBLIC_KEY/);
  assert.match(content, /docker-compose\.deploy\.yml/);
  assert.match(content, /nginx\/default\.conf/);
  assert.match(content, /scp/);
  assert.match(content, /ssh/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.deploy\.yml pull api/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.deploy\.yml up -d --no-build api nginx/);
  assert.match(content, /Wait for API container health/);
  assert.match(content, /DEPLOY_HEALTH_RETRIES/);
  assert.match(content, /DEPLOY_HEALTH_INTERVAL_SECONDS/);
  assert.match(content, /docker inspect/);
  assert.match(content, /logs --tail=100 api nginx/);
  assert.match(content, /Run deployment smoke test/);
  assert.match(content, /X-Request-ID/);
  assert.match(content, /\/health/);
  assert.match(content, /DEPLOY_PUBLIC_HEALTH_URL/);
  assert.match(content, /curl --fail/);
  assert.match(content, /Refusing to deploy a latest tag/);
  assert.doesNotMatch(content, /docker-compose\.infra\.yml/);
  assert.doesNotMatch(content, /pdm run migrate|alembic upgrade|pdm run seed|python -m app\.seed/);
  if (includePrivateKey) {
    assert.match(content, /JWT_PRIVATE_KEY/);
  } else {
    assert.doesNotMatch(content, /JWT_PRIVATE_KEY/);
  }
}

function assertPythonMigrateWorkflow(content: string) {
  assert.match(content, /name: Migrate/);
  assert.match(content, /workflow_dispatch:/);
  assert.match(content, /environment/);
  assert.match(content, /revision/);
  assert.match(content, /backup_confirmed/);
  assert.match(content, /actions\/checkout@v4/);
  assert.match(content, /SSH_PRIVATE_KEY/);
  assert.match(content, /DEPLOY_HOST/);
  assert.match(content, /DEPLOY_USER/);
  assert.match(content, /DEPLOY_PATH/);
  assert.match(content, /Refusing to run product migration without backup confirmation/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.deploy\.yml run --rm api alembic current/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.deploy\.yml run --rm api alembic upgrade/);
  assert.doesNotMatch(content, /pdm run seed|python -m app\.seed/);
  assert.doesNotMatch(content, /docker-compose\.infra\.yml/);
  assert.doesNotMatch(content, /JWT_PRIVATE_KEY/);
}

function assertPythonDeployCompose(content: string) {
  assert.match(content, /api:/);
  assert.match(content, /nginx:/);
  assert.match(content, /\$\{DOCKER_IMAGE_NAME\}:\$\{APP_VERSION\}/);
  assert.match(content, /env_file:/);
  assert.match(content, /\/health/);
  assert.match(content, /external: true/);
  assert.match(content, /DOCKER_NETWORK_NAME/);
  assert.doesNotMatch(content, /build:/);
}

function assertPythonInfraCompose(content: string) {
  assert.match(content, /postgres:16-alpine/);
  assert.match(content, /redis:7-alpine/);
  assert.match(content, /postgres_data/);
  assert.match(content, /redis_data/);
  assert.match(content, /appendonly yes/);
  assert.match(content, /DOCKER_NETWORK_NAME/);
  assert.doesNotMatch(content, /api:/);
}

function assertPythonDeployEnv(content: string, includePrivateKey: boolean) {
  assert.match(content, /DOCKER_IMAGE_NAME/);
  assert.match(content, /APP_VERSION/);
  assert.match(content, /CONTAINER_NAME/);
  assert.match(content, /APP_ENV/);
  assert.match(content, /APP_PORT/);
  assert.match(content, /NGINX_PORT/);
  assert.match(content, /DATABASE_URL/);
  assert.match(content, /REDIS_URL/);
  assert.match(content, /JWT_ISSUER/);
  assert.match(content, /JWT_AUDIENCE/);
  assert.match(content, /JWT_PUBLIC_KEY/);
  assert.match(content, /TOKEN_BLACKLIST_PREFIX/);
  assert.match(content, /SESSION_PREFIX/);
  assert.match(content, /DEPLOY_HEALTH_RETRIES/);
  assert.match(content, /DEPLOY_HEALTH_INTERVAL_SECONDS/);
  assert.match(content, /DEPLOY_PUBLIC_HEALTH_URL/);
  if (includePrivateKey) {
    assert.match(content, /JWT_PRIVATE_KEY/);
  } else {
    assert.doesNotMatch(content, /JWT_PRIVATE_KEY/);
  }
}

function assertPythonDeployReadme(content: string, includePrivateKey: boolean) {
  assert.match(content, /Release Deploy and Rollback/);
  assert.match(content, /GitHub Environments/);
  assert.match(content, /Docker Infra/);
  assert.match(content, /Tag Release/);
  assert.match(content, /Rollback/);
  assert.match(content, /Migrate workflow/);
  assert.match(content, /Post-deploy health check/);
  assert.match(content, /Smoke test/);
  assert.match(content, /Backup checklist/);
  assert.match(content, /Multi-service release/);
  assert.match(content, /Logging and monitoring/);
  assert.match(content, /Rollback playbook/);
  assert.match(content, /DEPLOY_PUBLIC_HEALTH_URL/);
  assert.match(content, /X-Request-ID/);
  assert.match(content, /Migration Policy/);
  assert.match(content, /backup_confirmed = true/);
  assert.match(content, /Seed Policy/);
  assert.match(content, /test-v1\.0\.1/);
  assert.match(content, /product-v1\.0\.1/);
  assert.match(content, /image_tag = product-v1\.0\.0/);
  assert.match(content, /docker compose --env-file \.env -f docker-compose\.deploy\.yml pull api/);
  assert.match(content, /Product does not auto-run seed/);
  if (includePrivateKey) {
    assert.match(content, /python-main` owns `JWT_PRIVATE_KEY/);
  } else {
    assert.match(content, /python-app` uses only `JWT_PUBLIC_KEY/);
  }
}

test("default template normalizes project names", () => {
  const files = createTemplateFiles({ projectName: "My App" });
  const packageJson = files.find((file) => file.path === "package.json");

  assert.ok(packageJson);
  assert.match(packageJson.content, /"name": "my-app"/);
  assert.deepEqual(
    files.map((file) => file.path),
    ["package.json", "README.md", "src/index.js"]
  );
  assert.match(files.find((file) => file.path === "README.md")?.content ?? "", /Generated by Tsu from the `default` template/);
});

test("monorepo template creates workspace files", () => {
  const files = createTemplateFiles({ projectName: "My Platform", templateName: "monorepo" });
  const paths = files.map((file) => file.path);
  const rootPackageJson = files.find((file) => file.path === "package.json");

  assert.ok(rootPackageJson);
  assert.match(rootPackageJson.content, /"name": "my-platform"/);
  assert.match(rootPackageJson.content, /"private": true/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.ok(paths.includes(".changeset/config.json"));
  assert.ok(paths.includes("cli/package.json"));
  assert.ok(paths.includes("components/package.json"));
  assert.ok(paths.includes("utils/package.json"));
  assert.ok(paths.includes("sdk/package.json"));
  assert.ok(paths.includes("tests/package.json"));
  assert.ok(paths.includes("script/package.json"));
  assert.match(files.find((file) => file.path === "cli/package.json")?.content ?? "", /"@tsuz\/template": "workspace:\*"/);
  assert.match(files.find((file) => file.path === "components/package.json")?.content ?? "", /"\.\/vue"/);
  assert.match(files.find((file) => file.path === "components/package.json")?.content ?? "", /"\.\/react"/);
  assert.match(files.find((file) => file.path === "utils/package.json")?.content ?? "", /"\.\/js"/);
  assert.match(files.find((file) => file.path === "README.md")?.content ?? "", /Generated by Tsu from the `monorepo` template/);
});

test("vue3 template creates vite-based app files", () => {
  const files = createTemplateFiles({ projectName: "My App", templateName: "vue3" });
  const paths = files.map((file) => file.path);
  const packageJson = files.find((file) => file.path === "package.json");
  const readme = files.find((file) => file.path === "README.md");
  const homeView = files.find((file) => file.path === "src/views/HomeView.vue");
  const dashboardStore = files.find((file) => file.path === "src/stores/dashboard.ts");
  const dashboardStoreTest = files.find((file) => file.path === "src/stores/dashboard.test.ts");

  assert.ok(packageJson);
  assert.ok(readme);
  assert.ok(homeView);
  assert.ok(dashboardStore);
  assert.ok(dashboardStoreTest);
  assert.match(packageJson.content, /"name": "my-app"/);
  assert.match(packageJson.content, /"dev": "vite"/);
  assert.match(packageJson.content, /"test": "vitest run"/);
  assert.match(packageJson.content, /"docker:build": "docker build -t my-app \./);
  assert.match(packageJson.content, /"docker:run": "docker run --rm -p 8080:80 my-app"/);
  assert.match(packageJson.content, /"@tsuz\/components": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"@tsuz\/sdk": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"@tsuz\/utils": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"vue": "\^3\.5\.13"/);
  assert.match(packageJson.content, /"pinia": "\^3\.0\.1"/);
  assert.match(packageJson.content, /"vue-router": "\^4\.5\.1"/);
  assert.match(packageJson.content, /"vitest": "\^3\.0\.5"/);
  assert.match(packageJson.content, /"@vue\/test-utils": "\^2\.4\.6"/);
  assert.match(packageJson.content, /"jsdom": "\^26\.0\.0"/);
  assert.match(packageJson.content, /"eslint": "\^9\.21\.0"/);
  assert.match(packageJson.content, /"@eslint\/js": "\^9\.21\.0"/);
  assert.match(packageJson.content, /"eslint-plugin-vue": "\^9\.32\.0"/);
  assert.match(packageJson.content, /"@types\/node": "\^20\.17\.57"/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.ok(paths.includes(".dockerignore"));
  assert.ok(paths.includes(".gitignore"));
  assert.ok(paths.includes("Dockerfile"));
  assert.ok(paths.includes("nginx.conf"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes("index.html"));
  assert.ok(paths.includes("vite.config.ts"));
  assert.ok(paths.includes("eslint.config.js"));
  assert.ok(paths.includes("tsconfig.json"));
  assert.ok(paths.includes("tsconfig.app.json"));
  assert.ok(paths.includes("src/env.d.ts"));
  assert.ok(paths.includes("src/main.ts"));
  assert.ok(paths.includes("src/App.vue"));
  assert.ok(paths.includes("src/router/index.ts"));
  assert.ok(paths.includes("src/stores/dashboard.ts"));
  assert.ok(paths.includes("src/stores/dashboard.test.ts"));
  assert.ok(paths.includes("src/styles/base.css"));
  assert.ok(paths.includes("src/styles/main.css"));
  assert.ok(paths.includes("src/views/HomeView.vue"));
  assert.ok(paths.includes("src/views/HomeView.test.ts"));
  assert.ok(paths.includes("src/views/AboutView.vue"));
  assert.ok(paths.includes("src/vite-env.d.ts"));
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /FROM node:20-alpine AS build/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /FROM nginx:1\.27-alpine/);
  assert.match(files.find((file) => file.path === "nginx.conf")?.content ?? "", /try_files \$uri \$uri\/ \/index\.html/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm install --frozen-lockfile/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm test/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm build/);
  assert.match(files.find((file) => file.path === "vite.config.ts")?.content ?? "", /vitest\/config/);
  assert.match(files.find((file) => file.path === "vite.config.ts")?.content ?? "", /environment: "jsdom"/);
  assert.match(files.find((file) => file.path === "eslint.config.js")?.content ?? "", /flat\/recommended/);
  assert.match(files.find((file) => file.path === "tsconfig.json")?.content ?? "", /"@\/\*": \[\s*"src\/\*"\s*\]/);
  assert.match(files.find((file) => file.path === "src/env.d.ts")?.content ?? "", /declare module "\*\.vue"/);
  assert.match(files.find((file) => file.path === "src/styles/main.css")?.content ?? "", /@import "\.\/base\.css";/);
  assert.match(files.find((file) => file.path === "src/App.vue")?.content ?? "", /Vue 3 \+ Router \+ Pinia/);
  assert.match(homeView.content, /@tsuz\/components\/vue/);
  assert.match(homeView.content, /useDashboardStore/);
  assert.match(homeView.content, /storeToRefs/);
  assert.match(homeView.content, /Dashboard starter/);
  assert.match(dashboardStore.content, /defineStore\("dashboard"/);
  assert.match(dashboardStore.content, /@tsuz\/sdk/);
  assert.match(dashboardStore.content, /@tsuz\/utils\/js/);
  assert.match(dashboardStore.content, /hasSummaries/);
  assert.match(dashboardStoreTest.content, /loads dashboard summaries/);
  assert.match(dashboardStoreTest.content, /stores a displayable error/);
  assert.match(files.find((file) => file.path === "src/views/HomeView.test.ts")?.content ?? "", /renders the dashboard starter actions/);
  assert.match(files.find((file) => file.path === "src/views/AboutView.vue")?.content ?? "", /Vitest tests, CI, and Docker/);
  assert.match(readme.content, /Generated by Tsu from the `vue3` template/);
  assert.match(readme.content, /Sample Dashboard Flow/);
  assert.match(readme.content, /Replacing the Mock API/);
  assert.match(readme.content, /Testing/);
});

test("react template creates vite-based app files", () => {
  const files = createTemplateFiles({ projectName: "React App", templateName: "react" });
  const paths = files.map((file) => file.path);
  const packageJson = files.find((file) => file.path === "package.json");
  const readme = files.find((file) => file.path === "README.md");
  const homeView = files.find((file) => file.path === "src/views/HomeView.tsx");
  const dashboardHook = files.find((file) => file.path === "src/hooks/useDashboardSummary.ts");

  assert.ok(packageJson);
  assert.ok(readme);
  assert.ok(homeView);
  assert.ok(dashboardHook);
  assert.match(packageJson.content, /"name": "react-app"/);
  assert.match(packageJson.content, /"dev": "vite"/);
  assert.match(packageJson.content, /"docker:build": "docker build -t react-app \./);
  assert.match(packageJson.content, /"docker:run": "docker run --rm -p 8080:80 react-app"/);
  assert.match(packageJson.content, /"@tsuz\/components": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"@tsuz\/sdk": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"@tsuz\/utils": "\^0\.2\.0"/);
  assert.match(packageJson.content, /"react": "\^19\.1\.0"/);
  assert.match(packageJson.content, /"react-dom": "\^19\.1\.0"/);
  assert.match(packageJson.content, /"react-router-dom": "\^7\.6\.2"/);
  assert.match(packageJson.content, /"@vitejs\/plugin-react": "\^4\.3\.4"/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.ok(paths.includes(".dockerignore"));
  assert.ok(paths.includes(".gitignore"));
  assert.ok(paths.includes("Dockerfile"));
  assert.ok(paths.includes("nginx.conf"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes("index.html"));
  assert.ok(paths.includes("vite.config.ts"));
  assert.ok(paths.includes("eslint.config.js"));
  assert.ok(paths.includes("tsconfig.json"));
  assert.ok(paths.includes("tsconfig.app.json"));
  assert.ok(paths.includes("src/main.tsx"));
  assert.ok(paths.includes("src/App.tsx"));
  assert.ok(paths.includes("src/hooks/useDashboardSummary.ts"));
  assert.ok(paths.includes("src/styles/base.css"));
  assert.ok(paths.includes("src/styles/main.css"));
  assert.ok(paths.includes("src/views/HomeView.tsx"));
  assert.ok(paths.includes("src/views/AboutView.tsx"));
  assert.ok(paths.includes("src/vite-env.d.ts"));
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /FROM node:20-alpine AS build/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /FROM nginx:1\.27-alpine/);
  assert.match(files.find((file) => file.path === "nginx.conf")?.content ?? "", /try_files \$uri \$uri\/ \/index\.html/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm install --frozen-lockfile/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm build/);
  assert.match(files.find((file) => file.path === "eslint.config.js")?.content ?? "", /react-hooks/);
  assert.match(files.find((file) => file.path === "src/App.tsx")?.content ?? "", /React \+ Router \+ Vite/);
  assert.match(homeView.content, /@tsuz\/components\/react/);
  assert.match(homeView.content, /useDashboardSummary/);
  assert.match(homeView.content, /Show empty/);
  assert.match(homeView.content, /Dashboard starter/);
  assert.match(dashboardHook.content, /@tsuz\/sdk/);
  assert.match(dashboardHook.content, /@tsuz\/utils\/js/);
  assert.match(dashboardHook.content, /DashboardSummaryMode = "success" \| "empty" \| "error"/);
  assert.match(dashboardHook.content, /hasSummaries/);
  assert.match(files.find((file) => file.path === "src/views/AboutView.tsx")?.content ?? "", /routing, TypeScript, CI, and Docker/);
  assert.match(readme.content, /Generated by Tsu from the `react` template/);
  assert.match(readme.content, /Sample Dashboard Flow/);
  assert.match(readme.content, /Replacing the Mock API/);
  assert.match(readme.content, /Adding Pages/);
});

test("python-main template creates auth service files", () => {
  const files = createTemplateFiles({ projectName: "Auth Service", templateName: "python-main" });
  const paths = files.map((file) => file.path);
  const pyproject = files.find((file) => file.path === "pyproject.toml");
  const readme = files.find((file) => file.path === "README.md");
  const envTest = files.find((file) => file.path === ".env.test.example");
  const envProduct = files.find((file) => file.path === ".env.product.example");
  const deployWorkflow = files.find((file) => file.path === ".github/workflows/deploy.yml");
  const migrateWorkflow = files.find((file) => file.path === ".github/workflows/migrate.yml");
  const deployCompose = files.find((file) => file.path === "docker-compose.deploy.yml");
  const infraCompose = files.find((file) => file.path === "docker-compose.infra.yml");
  const envDeploy = files.find((file) => file.path === ".env.deploy.example");

  assert.ok(pyproject);
  assert.ok(readme);
  assert.ok(envTest);
  assert.ok(envProduct);
  assert.ok(deployWorkflow);
  assert.ok(migrateWorkflow);
  assert.ok(deployCompose);
  assert.ok(infraCompose);
  assert.ok(envDeploy);
  assert.match(pyproject.content, /name = "auth-service"/);
  assert.match(pyproject.content, /fastapi/);
  assert.match(pyproject.content, /\[dependency-groups\]/);
  assert.match(pyproject.content, /\[tool\.pdm\.scripts\]/);
  assert.match(pyproject.content, /dev = "uvicorn app\.main:app --reload/);
  assert.match(pyproject.content, /gunicorn/);
  assert.match(pyproject.content, /uvicorn-worker/);
  assert.match(pyproject.content, /sqlalchemy/);
  assert.match(pyproject.content, /alembic/);
  assert.match(pyproject.content, /redis/);
  assert.match(pyproject.content, /bcrypt>=4\.0\.1,<5\.0\.0/);
  assert.match(readme.content, /Generated by Tsu from the `python-main` template/);
  assert.match(readme.content, /authentication center/);
  assert.ok(paths.includes("app/main.py"));
  assert.ok(paths.includes("app/api/auth.py"));
  assert.ok(paths.includes("app/api/health.py"));
  assert.ok(paths.includes("app/core/config.py"));
  assert.ok(paths.includes("app/core/logging.py"));
  assert.ok(paths.includes("app/core/database.py"));
  assert.ok(paths.includes("app/core/redis.py"));
  assert.ok(paths.includes("app/core/security.py"));
  assert.ok(paths.includes("app/models/user.py"));
  assert.ok(paths.includes("app/models/role.py"));
  assert.ok(paths.includes("app/models/permission.py"));
  assert.ok(paths.includes("app/models/session.py"));
  assert.ok(paths.includes("app/schemas/auth.py"));
  assert.ok(paths.includes("app/services/auth_service.py"));
  assert.ok(paths.includes("app/services/token_service.py"));
  assert.ok(paths.includes("app/services/refresh_token_service.py"));
  assert.ok(paths.includes("app/services/blacklist_service.py"));
  assert.ok(paths.includes("app/services/session_service.py"));
  assert.ok(paths.includes("alembic/env.py"));
  assert.ok(paths.includes("alembic/versions/0001_initial_auth_schema.py"));
  assert.ok(paths.includes("nginx/default.conf"));
  assert.ok(paths.includes("docker-compose.yml"));
  assert.ok(paths.includes("docker-compose.deploy.yml"));
  assert.ok(paths.includes("docker-compose.infra.yml"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes(".github/workflows/deploy.yml"));
  assert.ok(paths.includes(".github/workflows/migrate.yml"));
  assert.ok(paths.includes(".env.deploy.example"));
  assert.ok(paths.includes("tests/test_health.py"));
  assert.ok(paths.includes("tests/test_logging.py"));
  assert.ok(paths.includes("tests/test_redis_state_services.py"));
  assert.ok(paths.includes("tests/conftest.py"));
  assert.ok(paths.includes("tests/test_auth_api.py"));
  assert.ok(paths.includes("tests/test_token_service.py"));
  assert.ok(paths.includes("tests/test_refresh_token_service.py"));
  assert.ok(paths.includes("tests/test_auth_service.py"));
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /pdm install --prod --no-self/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /gunicorn app\.main:app/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /uvicorn_worker\.UvicornWorker/);
  assert.match(files.find((file) => file.path === "docker-compose.yml")?.content ?? "", /uvicorn app\.main:app --reload/);
  const workflow = files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "";
  const nginx = files.find((file) => file.path === "nginx/default.conf")?.content ?? "";
  assert.match(workflow, /pdm run alembic-current/);
  assert.match(workflow, /docker-build:/);
  assert.match(workflow, /docker build --tag/);
  assert.doesNotMatch(workflow, /deploy-test:|deploy-product:|TEST_DOCKER_REGISTRY_TOKEN|PRODUCT_DOCKER_REGISTRY_TOKEN/);
  assert.match(workflow, /TEST_JWT_PRIVATE_KEY/);
  assertPythonDeployWorkflow(deployWorkflow.content, true);
  assertPythonMigrateWorkflow(migrateWorkflow.content);
  assertPythonDeployCompose(deployCompose.content);
  assertPythonInfraCompose(infraCompose.content);
  assertPythonDeployEnv(envDeploy.content, true);
  assertPythonDeployReadme(readme.content, true);
  assert.match(readme.content, /GitHub Actions, Secrets, and Environments/);
  assert.match(readme.content, /## Auth API/);
  assert.match(readme.content, /POST \/auth\/login/);
  assert.match(readme.content, /POST \/auth\/refresh/);
  assert.match(readme.content, /GET \/auth\/me/);
  assert.match(readme.content, /## JWT Configuration/);
  assert.match(readme.content, /JWT_PRIVATE_KEY/);
  assert.match(readme.content, /escaped newline secrets/);
  assert.match(readme.content, /## Redis Token State/);
  assert.match(readme.content, /Refresh tokens are stored as SHA-256 hashes/);
  assert.match(readme.content, /REFRESH_TOKEN_REUSE_GRACE_SECONDS/);
  assert.match(readme.content, /revokes the session/);
  assert.match(readme.content, /## Database Migrations and Seed/);
  assert.match(readme.content, /alembic downgrade -1/);
  assert.match(readme.content, /alembic downgrade <revision_id>/);
  assert.match(readme.content, /pdm run seed/);
  assert.match(readme.content, /seed is idempotent/);
  assert.match(readme.content, /Product does not auto-run seed/);
  assert.match(readme.content, /## FAQ/);
  assert.match(nginx, /log_format safe_json/);
  assert.match(nginx, /Strict-Transport-Security/);
  assert.doesNotMatch(nginx, /\$http_authorization|\$http_cookie/);
  assert.match(envTest.content, /WEB_CONCURRENCY=1/);
  assert.match(envProduct.content, /WEB_CONCURRENCY=4/);
  assert.match(envTest.content, /LOG_FORMAT=json/);
  assert.match(envTest.content, /JWT_PRIVATE_KEY/);
  assert.match(envTest.content, /OPENAPI_ENABLED=true/);
  assert.match(envProduct.content, /OPENAPI_ENABLED=false/);
  assert.match(files.find((file) => file.path === "app/api/auth.py")?.content ?? "", /POST \/auth\/login|"\/login"/);
  assert.match(files.find((file) => file.path === "app/api/auth.py")?.content ?? "", /HTTP_401_UNAUTHORIZED/);
  const logging = files.find((file) => file.path === "app/core/logging.py")?.content ?? "";
  assert.match(logging, /redact_sensitive/);
  assert.match(logging, /_redacting_log_record_factory/);
  const authService = files.find((file) => file.path === "app/services/auth_service.py")?.content ?? "";
  assert.match(authService, /verify_password/);
  assert.match(authService, /select\(User\)/);
  assert.match(authService, /user_roles/);
  assert.match(authService, /role_permissions/);
  assert.match(authService, /AuthSession/);
  assert.match(authService, /rotate_refresh_token/);
  assert.match(authService, /RefreshTokenReuseError/);
  assert.doesNotMatch(authService, /password123/);
  const refreshTokenService = files.find((file) => file.path === "app/services/refresh_token_service.py")?.content ?? "";
  assert.match(refreshTokenService, /created_at/);
  assert.match(refreshTokenService, /replaced_by/);
  assert.match(refreshTokenService, /refresh_token_reuse_grace_seconds/);
  assert.match(refreshTokenService, /class RefreshTokenReuseError/);
  assert.match(files.find((file) => file.path === "app/services/session_service.py")?.content ?? "", /ensure_session_active/);
  assert.match(files.find((file) => file.path === "alembic/versions/0001_initial_auth_schema.py")?.content ?? "", /role_permissions/);
  assert.match(files.find((file) => file.path === "app/seed/__main__.py")?.content ?? "", /ensure_admin_user/);
  assert.match(files.find((file) => file.path === "app/seed/__main__.py")?.content ?? "", /DEFAULT_ADMIN_PASSWORD = "password123"/);
  assert.match(files.find((file) => file.path === "app/seed/__main__.py")?.content ?? "", /DEFAULT_PERMISSIONS/);
  assert.match(files.find((file) => file.path === "app/services/token_service.py")?.content ?? "", /jwt.encode/);
  assert.match(files.find((file) => file.path === "tests/test_auth_api.py")?.content ?? "", /test_login_failure_returns_401/);
  assert.match(files.find((file) => file.path === "tests/test_auth_api.py")?.content ?? "", /test_me_revoked_session_returns_401/);
  assert.match(files.find((file) => file.path === "tests/test_auth_service.py")?.content ?? "", /test_login_uses_db_user_password_and_rbac_claims/);
  assert.match(files.find((file) => file.path === "tests/test_auth_service.py")?.content ?? "", /test_login_failure_logs_reason_without_password/);
  assert.match(files.find((file) => file.path === "tests/test_auth_service.py")?.content ?? "", /test_refresh_reuse_revokes_db_session/);
  assert.match(files.find((file) => file.path === "tests/test_auth_service.py")?.content ?? "", /test_logout_blacklists_jti_revokes_redis_and_db_session/);
  assert.match(files.find((file) => file.path === "tests/test_logging.py")?.content ?? "", /test_security_logs_redact_sensitive_values/);
  assert.match(files.find((file) => file.path === "tests/test_redis_state_services.py")?.content ?? "", /test_blacklist_service_uses_configured_prefix_and_access_token_ttl/);
  assert.match(files.find((file) => file.path === "tests/test_refresh_token_service.py")?.content ?? "", /test_refresh_token_plaintext_is_not_stored_in_redis/);
  assert.match(files.find((file) => file.path === "tests/test_refresh_token_service.py")?.content ?? "", /test_rotated_refresh_token_after_grace_revokes_session/);
  assert.match(files.find((file) => file.path === "tests/test_token_service.py")?.content ?? "", /test_create_access_token_includes_required_payload_claims/);
  assert.match(files.find((file) => file.path === "tests/test_token_service.py")?.content ?? "", /\"iat\", \"exp\", \"jti\", \"iss\", \"aud\"/);
});

test("python-app template creates resource service files", () => {
  const files = createTemplateFiles({ projectName: "Backend API", templateName: "python-app" });
  const paths = files.map((file) => file.path);
  const pyproject = files.find((file) => file.path === "pyproject.toml");
  const readme = files.find((file) => file.path === "README.md");
  const envTest = files.find((file) => file.path === ".env.test.example");
  const deployWorkflow = files.find((file) => file.path === ".github/workflows/deploy.yml");
  const migrateWorkflow = files.find((file) => file.path === ".github/workflows/migrate.yml");
  const deployCompose = files.find((file) => file.path === "docker-compose.deploy.yml");
  const infraCompose = files.find((file) => file.path === "docker-compose.infra.yml");
  const envDeploy = files.find((file) => file.path === ".env.deploy.example");

  assert.ok(pyproject);
  assert.ok(readme);
  assert.ok(envTest);
  assert.ok(deployWorkflow);
  assert.ok(migrateWorkflow);
  assert.ok(deployCompose);
  assert.ok(infraCompose);
  assert.ok(envDeploy);
  assert.match(pyproject.content, /name = "backend-api"/);
  assert.match(pyproject.content, /\[tool\.pdm\.scripts\]/);
  assert.match(pyproject.content, /lint = "ruff check \./);
  assert.match(pyproject.content, /gunicorn/);
  assert.match(pyproject.content, /uvicorn-worker/);
  assert.match(pyproject.content, /bcrypt>=4\.0\.1,<5\.0\.0/);
  assert.match(readme.content, /Generated by Tsu from the `python-app` template/);
  assert.match(readme.content, /resource API service/);
  assert.ok(paths.includes("app/main.py"));
  assert.ok(paths.includes("app/api/example.py"));
  assert.ok(paths.includes("app/api/health.py"));
  assert.ok(paths.includes("app/deps/auth.py"));
  assert.ok(paths.includes("app/schemas/profile.py"));
  assert.ok(paths.includes("app/models/app_setting.py"));
  assert.ok(paths.includes("app/models/sample_profile.py"));
  assert.ok(paths.includes("app/services/blacklist_service.py"));
  assert.ok(paths.includes("app/services/session_service.py"));
  assert.ok(paths.includes("app/core/config.py"));
  assert.ok(paths.includes("app/core/logging.py"));
  assert.ok(paths.includes("alembic/env.py"));
  assert.ok(paths.includes("alembic/versions/0001_initial_app_schema.py"));
  assert.ok(paths.includes("nginx/default.conf"));
  assert.ok(paths.includes("docker-compose.yml"));
  assert.ok(paths.includes("docker-compose.deploy.yml"));
  assert.ok(paths.includes("docker-compose.infra.yml"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes(".github/workflows/deploy.yml"));
  assert.ok(paths.includes(".github/workflows/migrate.yml"));
  assert.ok(paths.includes(".env.deploy.example"));
  assert.ok(paths.includes("tests/conftest.py"));
  assert.ok(paths.includes("tests/test_logging.py"));
  assert.ok(paths.includes("tests/test_redis_state_services.py"));
  assert.ok(paths.includes("tests/test_profile_api.py"));
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /pip install --no-cache-dir pdm/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /gunicorn app\.main:app/);
  assert.match(files.find((file) => file.path === "docker-compose.yml")?.content ?? "", /uvicorn app\.main:app --reload/);
  const workflow = files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "";
  const nginx = files.find((file) => file.path === "nginx/default.conf")?.content ?? "";
  assert.match(workflow, /pdm run alembic-current/);
  assert.match(workflow, /docker-build:/);
  assert.match(workflow, /docker build --tag/);
  assert.doesNotMatch(workflow, /deploy-test:|deploy-product:|TEST_DOCKER_REGISTRY_TOKEN|PRODUCT_DOCKER_REGISTRY_TOKEN/);
  assert.doesNotMatch(workflow, /TEST_JWT_PRIVATE_KEY|PRODUCT_JWT_PRIVATE_KEY/);
  assertPythonDeployWorkflow(deployWorkflow.content, false);
  assertPythonMigrateWorkflow(migrateWorkflow.content);
  assertPythonDeployCompose(deployCompose.content);
  assertPythonInfraCompose(infraCompose.content);
  assertPythonDeployEnv(envDeploy.content, false);
  assertPythonDeployReadme(readme.content, false);
  assert.match(readme.content, /GitHub Actions, Secrets, and Environments/);
  assert.match(readme.content, /GitHub Environments/);
  assert.match(readme.content, /## Protected API Usage/);
  assert.match(readme.content, /Authorization: Bearer <access-token>/);
  assert.match(readme.content, /## Auth Integration with python-main/);
  assert.match(readme.content, /JWT_PUBLIC_KEY/);
  assert.match(readme.content, /JWT_ISSUER/);
  assert.match(readme.content, /JWT_AUDIENCE/);
  assert.match(readme.content, /Do not add `JWT_PRIVATE_KEY`/);
  assert.match(readme.content, /## Redis Blacklist/);
  assert.match(readme.content, /SESSION_PREFIX/);
  assert.match(readme.content, /sessions revoked by logout or refresh-token reuse/);
  assert.match(readme.content, /## Scopes and Permissions/);
  assert.match(readme.content, /require_scope\("user:read"\)/);
  assert.match(readme.content, /require_scopes\("a", "b"\)/);
  assert.match(readme.content, /require_any_scope\("a", "b"\)/);
  assert.match(readme.content, /require_role\("admin"\)/);
  assert.match(readme.content, /require_any_role\("admin", "operator"\)/);
  assert.match(readme.content, /## Database Migrations and Seed/);
  assert.match(readme.content, /alembic downgrade -1/);
  assert.match(readme.content, /pdm run seed/);
  assert.match(readme.content, /seed is idempotent/);
  assert.match(readme.content, /Product does not auto-run seed/);
  assert.match(readme.content, /## FAQ/);
  assert.match(nginx, /log_format safe_json/);
  assert.doesNotMatch(nginx, /\$http_authorization|\$http_cookie/);
  assert.match(envTest.content, /WEB_CONCURRENCY=1/);
  assert.match(envTest.content, /LOG_FORMAT=json/);
  assert.doesNotMatch(envTest.content, /JWT_PRIVATE_KEY/);
  assert.doesNotMatch(envTest.content, /REFRESH_TOKEN_EXPIRE_DAYS|REFRESH_TOKEN_PREFIX/);
  assert.match(envTest.content, /JWT_PUBLIC_KEY/);
  assert.match(envTest.content, /SESSION_PREFIX/);
  const appAuthDeps = files.find((file) => file.path === "app/deps/auth.py")?.content ?? "";
  assert.match(appAuthDeps, /jwt.decode/);
  assert.match(appAuthDeps, /Security\(security\)/);
  assert.match(appAuthDeps, /invalid_signature/);
  assert.match(appAuthDeps, /invalid_issuer/);
  assert.match(appAuthDeps, /invalid_audience/);
  assert.match(appAuthDeps, /SessionService/);
  assert.match(appAuthDeps, /ensure_session_active/);
  assert.match(appAuthDeps, /require_scope/);
  assert.match(appAuthDeps, /require_any_scope/);
  assert.match(appAuthDeps, /require_role/);
  assert.match(appAuthDeps, /require_any_role/);
  assert.match(files.find((file) => file.path === "alembic/versions/0001_initial_app_schema.py")?.content ?? "", /sample_profiles/);
  assert.match(files.find((file) => file.path === "app/seed/__main__.py")?.content ?? "", /ensure_setting/);
  assert.match(files.find((file) => file.path === "app/seed/__main__.py")?.content ?? "", /DEFAULT_SAMPLE_PROFILES/);
  assert.match(appAuthDeps, /HTTP_403_FORBIDDEN/);
  assert.doesNotMatch(appAuthDeps, /jwt.encode/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_requires_token/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_invalid_signature/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_revoked_session/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_insufficient_scope/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_malformed_roles_claim/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_malformed_roles_list_contents/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_profile_rejects_missing_required_claims/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_openapi_documents_profile_bearer_auth/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_require_any_scope_accepts_matching_scope/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_require_any_scope_rejects_missing_scope/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_require_any_role_accepts_matching_role/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_require_any_role_rejects_missing_role/);
  assert.match(files.find((file) => file.path === "tests/test_profile_api.py")?.content ?? "", /test_require_role_rejects_missing_role/);
  assert.match(files.find((file) => file.path === "tests/test_logging.py")?.content ?? "", /test_security_logs_redact_sensitive_values/);
  assert.match(files.find((file) => file.path === "tests/test_redis_state_services.py")?.content ?? "", /test_session_service_uses_configured_prefix_for_revocation/);
});

test("mfe template creates qiankun workspace files", () => {
  const files = createTemplateFiles({ projectName: "MFE Platform", templateName: "mfe" });
  const paths = files.map((file) => file.path);
  const packageJson = files.find((file) => file.path === "package.json");

  assert.ok(packageJson);
  assert.match(packageJson.content, /"name": "mfe-platform"/);
  assert.match(packageJson.content, /"dev": "pnpm --parallel --filter/);
  assert.match(packageJson.content, /"docker:build": "docker build -t mfe-platform \./);
  assert.match(packageJson.content, /"docker:run": "docker run --rm -p 7100:7100 -p 7101:7101 -p 7102:7102 mfe-platform"/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.ok(paths.includes("tsconfig.base.json"));
  assert.ok(paths.includes(".dockerignore"));
  assert.ok(paths.includes("Dockerfile"));
  assert.ok(paths.includes("nginx.conf"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes("apps/host/package.json"));
  assert.ok(paths.includes("apps/host/src/micro-apps.ts"));
  assert.ok(paths.includes("apps/subapp/package.json"));
  assert.ok(paths.includes("apps/subapp/src/lifecycle.ts"));
  assert.ok(paths.includes("apps/subapp-two/package.json"));
  assert.ok(paths.includes("apps/subapp-two/src/lifecycle.ts"));
  assert.ok(paths.includes("packages/shared/src/index.ts"));
  assert.ok(paths.includes("packages/ui/src/index.ts"));
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /FROM node:20-alpine AS build/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /COPY --from=build \/app\/apps\/host\/dist/);
  assert.match(files.find((file) => file.path === "Dockerfile")?.content ?? "", /COPY --from=build \/app\/apps\/subapp-two\/dist/);
  assert.match(files.find((file) => file.path === "nginx.conf")?.content ?? "", /listen 7100/);
  assert.match(files.find((file) => file.path === "nginx.conf")?.content ?? "", /listen 7102/);
  assert.match(files.find((file) => file.path === "nginx.conf")?.content ?? "", /Access-Control-Allow-Origin "\*"/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /run: pnpm install\n/);
  assert.doesNotMatch(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /--frozen-lockfile/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm test/);
  assert.match(files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "", /pnpm build/);
  assert.match(packageJson.content, /"test": "vitest run"/);
  assert.match(packageJson.content, /"lint": "eslint \. && pnpm -r lint"/);
  assert.ok(paths.includes("eslint.config.js"));
  assert.ok(paths.includes(".env.example"));
  assert.ok(paths.includes("apps/host/src/env.d.ts"));
  assert.ok(paths.includes("packages/shared/src/index.test.ts"));
  assert.match(files.find((file) => file.path === ".env.example")?.content ?? "", /VITE_ENTRY_SUBAPP_TWO=/);
  assert.match(files.find((file) => file.path === "apps/host/package.json")?.content ?? "", /"qiankun": "\^2\.10\.16"/);
  assert.match(files.find((file) => file.path === "apps/host/src/micro-apps.ts")?.content ?? "", /microAppMetas\.map/);
  assert.match(files.find((file) => file.path === "apps/host/src/micro-apps.ts")?.content ?? "", /VITE_ENTRY_/);
  assert.match(files.find((file) => file.path === "apps/host/src/micro-apps.ts")?.content ?? "", /container: "#subapp-container"/);
  assert.match(files.find((file) => file.path === "apps/host/src/main.ts")?.content ?? "", /setDefaultMountApp/);
  assert.match(files.find((file) => file.path === "apps/host/src/App.vue")?.content ?? "", /id="subapp-container"/);
  assert.match(files.find((file) => file.path === "apps/host/src/App.vue")?.content ?? "", /hostEventBus\.emit/);
  assert.match(files.find((file) => file.path === "apps/host/src/App.vue")?.content ?? "", /matchesActiveRule/);
  assert.doesNotMatch(files.find((file) => file.path === "apps/host/src/App.vue")?.content ?? "", /startsWith\(app\.activeRule\)/);
  assert.match(files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "", /subapp-two/);
  assert.match(files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "", /7102/);
  assert.match(files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "", /export function createBrowserEventBus/);
  assert.match(files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "", /export const hostEventBus/);
  assert.match(files.find((file) => file.path === "packages/ui/src/index.ts")?.content ?? "", /export const BrandBadge/);
  assert.match(files.find((file) => file.path === "packages/ui/package.json")?.content ?? "", /"vue": "\^3\.5\.13"/);
  assert.match(files.find((file) => file.path === "apps/subapp/package.json")?.content ?? "", /"vite-plugin-qiankun": "\^1\.0\.15"/);
  assert.match(files.find((file) => file.path === "apps/subapp/src/lifecycle.ts")?.content ?? "", /export function mount/);
  assert.match(files.find((file) => file.path === "apps/subapp/src/lifecycle.ts")?.content ?? "", /export function update/);
  assert.match(files.find((file) => file.path === "apps/subapp/src/main.ts")?.content ?? "", /bootstrap, mount, unmount, update/);
  assert.match(files.find((file) => file.path === "apps/subapp/src/App.vue")?.content ?? "", /hostEventBus\.on/);
  assert.match(files.find((file) => file.path === "apps/subapp-two/package.json")?.content ?? "", /"vite-plugin-qiankun": "\^1\.0\.15"/);
  assert.match(files.find((file) => file.path === "apps/subapp-two/src/App.vue")?.content ?? "", /Sub App Two is ready/);
  assert.match(files.find((file) => file.path === "README.md")?.content ?? "", /Generated by Tsu from the `mfe` template/);
  const readme = files.find((file) => file.path === "README.md")?.content ?? "";

  assert.match(readme, /Sub App Entry Configuration/);
  assert.match(readme, /Host and Sub App Communication/);
  assert.match(readme, /Adding a Sub App/);
  assert.match(readme, /Host\/Sub App Communication Example/);
  assert.match(readme, /Docker and nginx Deployment Notes/);
  assert.match(readme, /Remote Template Version Verification/);
  assert.match(readme, /tsu-cli init verify-mfe --template mfe --version <template-version> --repo <owner\/repo>/);
  assert.match(readme, /Micro Frontend Choice Guide/);
});

test("mfe-main template creates React qiankun host skeleton files", () => {
  const files = createTemplateFiles({ projectName: "MFE Main", templateName: "mfe-main" });
  const paths = files.map((file) => file.path);
  const packageJson = files.find((file) => file.path === "package.json");
  const appPackageJson = files.find((file) => file.path === "apps/main/package.json");
  const workspace = files.find((file) => file.path === "pnpm-workspace.yaml")?.content ?? "";
  const appTsConfig = files.find((file) => file.path === "apps/main/tsconfig.json")?.content ?? "";
  const appViteConfig = files.find((file) => file.path === "apps/main/vite.config.ts")?.content ?? "";
  const appEnvExample = files.find((file) => file.path === "apps/main/.env.example")?.content ?? "";
  const readme = files.find((file) => file.path === "README.md")?.content ?? "";
  const app = files.find((file) => file.path === "apps/main/src/App.tsx")?.content ?? "";
  const main = files.find((file) => file.path === "apps/main/src/main.tsx")?.content ?? "";
  const styles = files.find((file) => file.path === "apps/main/src/styles/main.css")?.content ?? "";
  const viteEnv = files.find((file) => file.path === "apps/main/src/vite-env.d.ts")?.content ?? "";
  const microAppConfig = files.find((file) => file.path === "apps/main/src/micro-apps/config.ts")?.content ?? "";
  const microAppRegistry = files.find((file) => file.path === "apps/main/src/micro-apps/registry.ts")?.content ?? "";
  const authStore = files.find((file) => file.path === "apps/main/src/stores/auth.store.ts")?.content ?? "";
  const apiClient = files.find((file) => file.path === "apps/main/src/services/api-client.ts")?.content ?? "";
  const sharedSource = files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "";
  const uiSource = files.find((file) => file.path === "packages/ui/src/index.tsx")?.content ?? "";
  const apiSource = files.find((file) => file.path === "packages/api/src/index.ts")?.content ?? "";
  const eslintConfig = files.find((file) => file.path === "eslint.config.js")?.content ?? "";
  const prettierConfig = files.find((file) => file.path === "prettier.config.js")?.content ?? "";
  const dockerfile = files.find((file) => file.path === "Dockerfile")?.content ?? "";
  const nginxConfig = files.find((file) => file.path === "nginx/nginx.conf")?.content ?? "";
  const compose = files.find((file) => file.path === "docker-compose.yml")?.content ?? "";
  const deployEnv = files.find((file) => file.path === ".env.deploy.example")?.content ?? "";
  const dockerignore = files.find((file) => file.path === ".dockerignore")?.content ?? "";
  const workflow = files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "";
  const deployWorkflow = files.find((file) => file.path === ".github/workflows/deploy.yml")?.content ?? "";

  assert.ok(packageJson);
  assert.ok(appPackageJson);
  assert.match(packageJson.content, /"name": "mfe-main"/);
  assert.match(packageJson.content, /"dev": "pnpm --filter mfe-main-main dev"/);
  assert.match(packageJson.content, /"build": "turbo run build"/);
  assert.match(packageJson.content, /"lint": "eslint \. --max-warnings 0 && turbo run lint"/);
  assert.match(packageJson.content, /"test": "turbo run test"/);
  assert.match(packageJson.content, /"test:e2e": "playwright test"/);
  assert.match(packageJson.content, /"docker:build": "docker build -t mfe-main:\$\{APP_VERSION:-local\} \./);
  assert.match(packageJson.content, /"docker:run": "docker run --rm -p 7200:80 mfe-main:\$\{APP_VERSION:-local\}"/);
  assert.match(packageJson.content, /"compose:up": "docker compose up --build"/);
  assert.match(packageJson.content, /"compose:down": "docker compose down"/);
  assert.match(packageJson.content, /"format": "prettier --ignore-unknown --write/);
  assert.match(packageJson.content, /"format:check": "prettier --ignore-unknown --check/);
  assert.match(packageJson.content, /\.github\/workflows\/deploy\.yml/);
  assert.match(packageJson.content, /"@eslint\/js"/);
  assert.match(packageJson.content, /"@playwright\/test"/);
  assert.match(packageJson.content, /"eslint-plugin-react-hooks"/);
  assert.match(packageJson.content, /"eslint-plugin-react-refresh"/);
  assert.match(packageJson.content, /"typescript-eslint"/);
  assert.match(packageJson.content, /"prettier"/);
  assert.match(appPackageJson.content, /"name": "mfe-main-main"/);
  assert.match(appPackageJson.content, /"react": "\^19\.1\.0"/);
  assert.match(appPackageJson.content, /"qiankun": "\^2\.10\.16"/);
  assert.match(appPackageJson.content, /"@tanstack\/react-query"/);
  assert.match(appPackageJson.content, /"@tsuz\/api": "workspace:\*"/);
  assert.match(appPackageJson.content, /"@tsuz\/shared": "workspace:\*"/);
  assert.match(appPackageJson.content, /"@tsuz\/ui": "workspace:\*"/);
  assert.match(appPackageJson.content, /"zustand"/);
  assert.match(appPackageJson.content, /"antd"/);
  assert.match(appPackageJson.content, /"tailwindcss"/);
  assert.match(appPackageJson.content, /"postcss"/);
  assert.match(appPackageJson.content, /"autoprefixer"/);
  assert.match(appPackageJson.content, /"@testing-library\/jest-dom"/);
  assert.match(appPackageJson.content, /"@testing-library\/react"/);
  assert.match(appPackageJson.content, /"@testing-library\/user-event"/);
  assert.match(appPackageJson.content, /"jsdom"/);
  assert.match(appPackageJson.content, /"test": "vitest run"/);
  assert.match(appPackageJson.content, /"vitest": "\^3\.0\.5"/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.match(workspace, /packages\/\*/);
  assert.ok(paths.includes("turbo.json"));
  assert.ok(paths.includes("tsconfig.base.json"));
  assert.ok(paths.includes(".dockerignore"));
  assert.ok(paths.includes(".env.deploy.example"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes(".github/workflows/deploy.yml"));
  assert.ok(paths.includes("Dockerfile"));
  assert.ok(paths.includes("nginx/nginx.conf"));
  assert.ok(paths.includes("docker-compose.yml"));
  assert.ok(paths.includes(".gitignore"));
  assert.ok(paths.includes("eslint.config.js"));
  assert.ok(paths.includes("prettier.config.js"));
  assert.ok(paths.includes(".prettierignore"));
  assert.ok(paths.includes("playwright.config.ts"));
  assert.ok(paths.includes("e2e/host-login.spec.ts"));
  assert.ok(paths.includes("e2e/host-load-subapp.spec.ts"));
  assert.ok(paths.includes("apps/main/.env.example"));
  assert.ok(paths.includes("apps/main/package.json"));
  assert.ok(paths.includes("apps/main/index.html"));
  assert.ok(paths.includes("apps/main/vite.config.ts"));
  assert.ok(paths.includes("apps/main/tailwind.config.js"));
  assert.ok(paths.includes("apps/main/postcss.config.js"));
  assert.ok(paths.includes("apps/main/tsconfig.json"));
  assert.ok(paths.includes("apps/main/src/test/setup.ts"));
  assert.ok(paths.includes("apps/main/src/main.tsx"));
  assert.ok(paths.includes("apps/main/src/App.tsx"));
  assert.ok(paths.includes("apps/main/src/components/RequireAuth.tsx"));
  assert.ok(paths.includes("apps/main/src/micro-apps/config.ts"));
  assert.ok(paths.includes("apps/main/src/micro-apps/config.test.ts"));
  assert.ok(paths.includes("apps/main/src/micro-apps/registry.ts"));
  assert.ok(paths.includes("apps/main/src/pages/LoginPage.tsx"));
  assert.ok(paths.includes("apps/main/src/pages/LoginPage.test.tsx"));
  assert.ok(paths.includes("apps/main/src/providers/AppProviders.tsx"));
  assert.ok(paths.includes("apps/main/src/providers/query-client.ts"));
  assert.ok(paths.includes("apps/main/src/services/api-client.ts"));
  assert.ok(paths.includes("apps/main/src/services/auth.service.ts"));
  assert.ok(paths.includes("apps/main/src/services/auth.service.test.ts"));
  assert.ok(paths.includes("apps/main/src/stores/auth.store.ts"));
  assert.ok(paths.includes("apps/main/src/styles/main.css"));
  assert.ok(paths.includes("apps/main/src/vite-env.d.ts"));
  assert.ok(paths.includes("packages/shared/package.json"));
  assert.ok(paths.includes("packages/shared/tsconfig.json"));
  assert.ok(paths.includes("packages/shared/src/index.ts"));
  assert.ok(paths.includes("packages/shared/src/index.test.ts"));
  assert.ok(paths.includes("packages/ui/package.json"));
  assert.ok(paths.includes("packages/ui/tsconfig.json"));
  assert.ok(paths.includes("packages/ui/src/index.tsx"));
  assert.ok(paths.includes("packages/api/package.json"));
  assert.ok(paths.includes("packages/api/tsconfig.json"));
  assert.ok(paths.includes("packages/api/src/index.ts"));
  assert.ok(paths.includes("packages/api/src/index.test.ts"));
  assert.ok(!paths.includes("apps/main/src/types/auth.ts"));
  assert.match(styles, /antd\/dist\/reset\.css/);
  assert.match(styles, /@tailwind base/);
  assert.match(styles, /@tailwind components/);
  assert.match(styles, /@tailwind utilities/);
  assert.match(eslintConfig, /react-hooks/);
  assert.match(eslintConfig, /react-refresh/);
  assert.match(eslintConfig, /packages\/ui/);
  assert.match(prettierConfig, /printWidth/);
  assert.match(dockerfile, /FROM node:20-alpine AS build/);
  assert.match(dockerfile, /FROM nginx:1\.27-alpine/);
  assert.match(dockerfile, /ARG VITE_API_BASE_URL=\/api/);
  assert.match(dockerfile, /ARG VITE_MFE_APP_ENTRY=\/\/localhost:7201/);
  assert.match(dockerfile, /ARG VITE_APP_ENV=production/);
  assert.match(dockerfile, /COPY --from=build \/app\/apps\/main\/dist \/usr\/share\/nginx\/html/);
  assert.match(nginxConfig, /try_files \$uri \$uri\/ \/index\.html/);
  assert.match(nginxConfig, /Cache-Control "no-store, no-cache, must-revalidate"/);
  assert.match(nginxConfig, /Cache-Control "public, immutable"/);
  assert.doesNotMatch(nginxConfig, /Access-Control-Allow-Origin/);
  assert.match(compose, /\$\{DOCKER_IMAGE_NAME:-mfe-main\}:\$\{APP_VERSION:-local\}/);
  assert.match(compose, /\$\{CONTAINER_NAME:-mfe-main\}/);
  assert.match(compose, /"\$\{APP_PORT:-7200\}:80"/);
  assert.match(compose, /VITE_API_BASE_URL: \$\{VITE_API_BASE_URL:-\/api\}/);
  assert.match(compose, /VITE_MFE_APP_ENTRY: \$\{VITE_MFE_APP_ENTRY:-\/\/localhost:7201\}/);
  assert.match(compose, /VITE_APP_ENV: \$\{APP_ENV:-local\}/);
  assert.match(deployEnv, /DOCKER_IMAGE_NAME=mfe-main/);
  assert.match(deployEnv, /APP_VERSION=local/);
  assert.match(deployEnv, /APP_PORT=7200/);
  assert.match(deployEnv, /VITE_APP_ENV|APP_ENV=local/);
  assert.match(deployEnv, /VITE_MFE_APP_ENTRY=\/\/localhost:7201/);
  assert.match(dockerignore, /apps\/\*\/dist/);
  assert.match(dockerignore, /!\.env\.deploy\.example/);
  assertMfeCiWorkflow(workflow);
  assertMfeDeployWorkflow(deployWorkflow);
  assert.doesNotMatch(deployWorkflow, /:latest/);
  assert.match(appEnvExample, /VITE_APP_ENV=local/);
  assert.match(files.find((file) => file.path === "playwright.config.ts")?.content ?? "", /MFE_INTEGRATION_E2E/);
  assert.match(files.find((file) => file.path === "e2e/host-login.spec.ts")?.content ?? "", /Waiting for mfe-app/);
  assert.match(files.find((file) => file.path === "e2e/host-load-subapp.spec.ts")?.content ?? "", /Auth bridge: provided/);
  assert.match(files.find((file) => file.path === "apps/main/src/test/setup.ts")?.content ?? "", /@testing-library\/jest-dom/);
  assert.match(files.find((file) => file.path === "apps/main/src/pages/LoginPage.test.tsx")?.content ?? "", /renders demo credentials/);
  assert.match(appTsConfig, /@tsuz\/shared/);
  assert.match(appTsConfig, /@tsuz\/ui/);
  assert.match(appTsConfig, /@tsuz\/api/);
  assert.match(appViteConfig, /@tsuz\/shared/);
  assert.match(appViteConfig, /@tsuz\/ui/);
  assert.match(appViteConfig, /@tsuz\/api/);
  assert.match(appViteConfig, /vitest\/config/);
  assert.match(appViteConfig, /environment: "jsdom"/);
  assert.match(appViteConfig, /setupFiles: "\.\/src\/test\/setup\.ts"/);
  assert.match(appViteConfig, /dedupe: \["react", "react-dom"\]/);
  assert.match(main, /registerMicroFrontendApps/);
  assert.match(app, /LoginPage/);
  assert.match(app, /RequireAuth/);
  assert.match(app, /useEffect/);
  assert.match(app, /PopStateEvent\("popstate"\)/);
  assert.match(app, /id="subapp-container"/);
  assert.match(app, /getAccessToken/);
  assert.doesNotMatch(app, /qiankun will mount sub applications here in Phase 3/);
  assert.doesNotMatch(app, /This Phase 2 host skeleton/);
  assert.match(viteEnv, /VITE_API_BASE_URL/);
  assert.match(viteEnv, /VITE_MFE_APP_ENTRY/);
  assert.match(app, /@tsuz\/ui/);
  assert.match(app, /MFE_APP_ROUTE/);
  assert.match(microAppConfig, /@tsuz\/shared/);
  assert.match(microAppConfig, /VITE_MFE_APP_ENTRY/);
  assert.match(microAppConfig, /VITE_API_BASE_URL/);
  assert.match(microAppConfig, /matchesActiveRoute/);
  assert.match(microAppConfig, /getAccessToken/);
  assert.match(microAppConfig, /getCurrentUser/);
  assert.match(microAppConfig, /logout/);
  assert.match(microAppConfig, /#subapp-container/);
  assert.match(microAppRegistry, /registerMicroApps/);
  assert.match(microAppRegistry, /start\(\{ prefetch: false \}\)/);
  assert.match(authStore, /@tsuz\/shared/);
  assert.match(authStore, /authBridge/);
  assert.match(authStore, /getAccessToken/);
  assert.match(authStore, /getCurrentUser/);
  assert.match(apiClient, /createApiClient/);
  assert.match(apiClient, /DEFAULT_API_BASE_URL/);
  assert.match(sharedSource, /export interface CurrentUser/);
  assert.match(sharedSource, /export interface AuthSession/);
  assert.match(sharedSource, /export interface MicroAppProps/);
  assert.match(sharedSource, /MFE_APP_ROUTE/);
  assert.match(sharedSource, /DEFAULT_API_BASE_URL/);
  assert.match(sharedSource, /export function classNames/);
  assert.match(sharedSource, /export const cx/);
  assert.match(sharedSource, /export function matchesActiveRoute/);
  assert.match(uiSource, /export function Logo/);
  assert.match(uiSource, /export function PageContainer/);
  assert.match(uiSource, /export function EmptyState/);
  assert.match(uiSource, /export function ErrorState/);
  assert.match(apiSource, /export function createApiClient/);
  assert.match(apiSource, /export class ApiError/);
  assert.match(readme, /Generated by Tsu from the `mfe-main` template/);
  assert.match(readme, /production-ready React qiankun host shell starter/);
  assert.match(readme, /Generate the Project/);
  assert.match(readme, /Local development/);
  assert.match(readme, /Local quality gates/);
  assert.match(readme, /tsu-cli init mfe-main-platform --template mfe-main/);
  assert.match(readme, /GitHub Actions CI/);
  assert.match(readme, /GitHub Actions Deploy/);
  assert.match(readme, /GitHub Environments/);
  assert.match(readme, /test-v\*\.\*\.\*/);
  assert.match(readme, /product-v\*\.\*\.\*/);
  assert.match(readme, /test-v1\.0\.1/);
  assert.match(readme, /product-v1\.0\.1/);
  assert.match(readme, /workflow_dispatch/);
  assert.match(readme, /image_tag/);
  assert.match(readme, /rollback/);
  assert.match(readme, /docker compose up -d --no-build/);
  assert.match(readme, /deploy\.yml automatically uploads docker-compose\.yml/);
  assert.match(readme, /DOCKER_REGISTRY_TOKEN/);
  assert.match(readme, /SSH_PRIVATE_KEY/);
  assert.match(readme, /pnpm format:check/);
  assert.match(readme, /Testing Library/);
  assert.match(readme, /Playwright/);
  assert.match(readme, /Shared Workspace Packages/);
  assert.match(readme, /Demo credentials/);
  assert.match(readme, /VITE_API_BASE_URL is a build-time variable/);
  assert.match(readme, /VITE_MFE_APP_ENTRY/);
  assert.match(readme, /Docker and nginx/);
  assert.match(readme, /Docker Compose/);
  assert.match(readme, /APP_VERSION/);
  assert.match(readme, /VITE_APP_ENV/);
  assert.match(readme, /pnpm docker:build/);
  assert.match(readme, /pnpm compose:up/);
  assert.match(readme, /pnpm test/);
  assert.match(readme, /pnpm test:e2e/);
  assert.match(readme, /host-load-subapp\.spec\.ts/);
  assert.match(readme, /\.github\/workflows\/ci\.yml/);
  assert.doesNotMatch(readme, /Phase 4 adds shared, ui, and api workspace packages/);
  assert.doesNotMatch(readme, /Phase 3 React qiankun host shell starter/);
  assert.doesNotMatch(readme, /Phase 2 React qiankun host shell starter/);
  assert.doesNotMatch(readme, /Phase 1 React qiankun host shell skeleton/);
});

test("mfe-app template creates React qiankun sub app skeleton files", () => {
  const files = createTemplateFiles({ projectName: "MFE Business", templateName: "mfe-app" });
  const paths = files.map((file) => file.path);
  const packageJson = files.find((file) => file.path === "package.json");
  const appPackageJson = files.find((file) => file.path === "apps/app/package.json");
  const workspace = files.find((file) => file.path === "pnpm-workspace.yaml")?.content ?? "";
  const turbo = files.find((file) => file.path === "turbo.json")?.content ?? "";
  const appTsConfig = files.find((file) => file.path === "apps/app/tsconfig.json")?.content ?? "";
  const appViteConfig = files.find((file) => file.path === "apps/app/vite.config.ts")?.content ?? "";
  const appEnvExample = files.find((file) => file.path === "apps/app/.env.example")?.content ?? "";
  const readme = files.find((file) => file.path === "README.md")?.content ?? "";
  const app = files.find((file) => file.path === "apps/app/src/App.tsx")?.content ?? "";
  const businessHomePage = files.find((file) => file.path === "apps/app/src/pages/BusinessHomePage.tsx")?.content ?? "";
  const appProviders = files.find((file) => file.path === "apps/app/src/providers/AppProviders.tsx")?.content ?? "";
  const queryClient = files.find((file) => file.path === "apps/app/src/providers/query-client.ts")?.content ?? "";
  const appStore = files.find((file) => file.path === "apps/app/src/stores/app.store.ts")?.content ?? "";
  const businessHomeQuery = files.find((file) => file.path === "apps/app/src/queries/business-home.query.ts")?.content ?? "";
  const bootstrap = files.find((file) => file.path === "apps/app/src/bootstrap.tsx")?.content ?? "";
  const main = files.find((file) => file.path === "apps/app/src/main.tsx")?.content ?? "";
  const qiankun = files.find((file) => file.path === "apps/app/src/qiankun.ts")?.content ?? "";
  const apiClient = files.find((file) => file.path === "apps/app/src/services/api-client.ts")?.content ?? "";
  const sharedSource = files.find((file) => file.path === "packages/shared/src/index.ts")?.content ?? "";
  const uiSource = files.find((file) => file.path === "packages/ui/src/index.tsx")?.content ?? "";
  const apiSource = files.find((file) => file.path === "packages/api/src/index.ts")?.content ?? "";
  const viteEnv = files.find((file) => file.path === "apps/app/src/vite-env.d.ts")?.content ?? "";
  const dockerfile = files.find((file) => file.path === "Dockerfile")?.content ?? "";
  const nginxConfig = files.find((file) => file.path === "nginx/nginx.conf")?.content ?? "";
  const compose = files.find((file) => file.path === "docker-compose.yml")?.content ?? "";
  const deployEnv = files.find((file) => file.path === ".env.deploy.example")?.content ?? "";
  const dockerignore = files.find((file) => file.path === ".dockerignore")?.content ?? "";
  const prettierConfig = files.find((file) => file.path === "prettier.config.js")?.content ?? "";
  const workflow = files.find((file) => file.path === ".github/workflows/ci.yml")?.content ?? "";
  const deployWorkflow = files.find((file) => file.path === ".github/workflows/deploy.yml")?.content ?? "";

  assert.ok(packageJson);
  assert.ok(appPackageJson);
  assert.match(packageJson.content, /"name": "mfe-business"/);
  assert.match(packageJson.content, /"dev": "pnpm --filter mfe-business-app dev"/);
  assert.match(packageJson.content, /"build": "turbo run build"/);
  assert.match(packageJson.content, /"test": "turbo run test"/);
  assert.match(packageJson.content, /"test:e2e": "playwright test"/);
  assert.match(packageJson.content, /"format": "prettier --ignore-unknown --write/);
  assert.match(packageJson.content, /"format:check": "prettier --ignore-unknown --check/);
  assert.match(packageJson.content, /\.github\/workflows\/deploy\.yml/);
  assert.match(packageJson.content, /"docker:build": "docker build -t mfe-business:\$\{APP_VERSION:-local\} \./);
  assert.match(packageJson.content, /"docker:run": "docker run --rm -p 7201:80 mfe-business:\$\{APP_VERSION:-local\}"/);
  assert.match(packageJson.content, /"compose:up": "docker compose up --build"/);
  assert.match(packageJson.content, /"compose:down": "docker compose down"/);
  assert.match(packageJson.content, /"@playwright\/test"/);
  assert.match(packageJson.content, /"prettier"/);
  assert.match(appPackageJson.content, /"name": "mfe-business-app"/);
  assert.match(appPackageJson.content, /"react": "\^19\.1\.0"/);
  assert.match(appPackageJson.content, /"qiankun": "\^2\.10\.16"/);
  assert.match(appPackageJson.content, /"vite-plugin-qiankun": "\^1\.0\.15"/);
  assert.match(appPackageJson.content, /"@tanstack\/react-query"/);
  assert.match(appPackageJson.content, /"@tsuz\/api": "workspace:\*"/);
  assert.match(appPackageJson.content, /"@tsuz\/shared": "workspace:\*"/);
  assert.match(appPackageJson.content, /"@tsuz\/ui": "workspace:\*"/);
  assert.match(appPackageJson.content, /"zustand"/);
  assert.match(appPackageJson.content, /"antd"/);
  assert.match(appPackageJson.content, /"@testing-library\/jest-dom"/);
  assert.match(appPackageJson.content, /"@testing-library\/react"/);
  assert.match(appPackageJson.content, /"@testing-library\/user-event"/);
  assert.match(appPackageJson.content, /"jsdom"/);
  assert.match(appPackageJson.content, /"test": "vitest run"/);
  assert.match(appPackageJson.content, /"vitest": "\^3\.0\.5"/);
  assert.ok(paths.includes("README.md"));
  assert.ok(paths.includes("pnpm-workspace.yaml"));
  assert.match(workspace, /packages\/\*/);
  assert.ok(paths.includes("turbo.json"));
  assert.match(turbo, /"test"/);
  assert.ok(paths.includes("tsconfig.base.json"));
  assert.ok(paths.includes(".dockerignore"));
  assert.ok(paths.includes(".env.deploy.example"));
  assert.ok(paths.includes(".github/workflows/ci.yml"));
  assert.ok(paths.includes(".github/workflows/deploy.yml"));
  assert.ok(paths.includes("Dockerfile"));
  assert.ok(paths.includes("nginx/nginx.conf"));
  assert.ok(paths.includes("docker-compose.yml"));
  assert.ok(paths.includes(".gitignore"));
  assert.ok(paths.includes("prettier.config.js"));
  assert.ok(paths.includes(".prettierignore"));
  assert.ok(paths.includes("playwright.config.ts"));
  assert.ok(paths.includes("e2e/standalone.spec.ts"));
  assert.ok(paths.includes("apps/app/package.json"));
  assert.ok(paths.includes("apps/app/index.html"));
  assert.ok(paths.includes("apps/app/vite.config.ts"));
  assert.ok(paths.includes("apps/app/tsconfig.json"));
  assert.ok(paths.includes("apps/app/src/test/setup.ts"));
  assert.ok(paths.includes("apps/app/src/main.tsx"));
  assert.ok(paths.includes("apps/app/src/App.tsx"));
  assert.ok(paths.includes("apps/app/src/bootstrap.tsx"));
  assert.ok(paths.includes("apps/app/src/qiankun.ts"));
  assert.ok(paths.includes("apps/app/src/pages/BusinessHomePage.tsx"));
  assert.ok(paths.includes("apps/app/src/pages/BusinessHomePage.test.tsx"));
  assert.ok(paths.includes("apps/app/src/providers/AppProviders.tsx"));
  assert.ok(paths.includes("apps/app/src/providers/query-client.ts"));
  assert.ok(paths.includes("apps/app/src/queries/business-home.query.ts"));
  assert.ok(paths.includes("apps/app/src/stores/app.store.ts"));
  assert.ok(paths.includes("apps/app/src/services/api-client.ts"));
  assert.ok(paths.includes("apps/app/src/qiankun.test.ts"));
  assert.ok(paths.includes("apps/app/src/services/api-client.test.ts"));
  assert.ok(paths.includes("apps/app/src/stores/app.store.test.ts"));
  assert.ok(paths.includes("apps/app/src/queries/business-home.query.test.ts"));
  assert.ok(paths.includes("apps/app/src/styles/main.css"));
  assert.ok(paths.includes("apps/app/src/vite-env.d.ts"));
  assert.ok(paths.includes("packages/shared/package.json"));
  assert.ok(paths.includes("packages/shared/tsconfig.json"));
  assert.ok(paths.includes("packages/shared/src/index.ts"));
  assert.ok(paths.includes("packages/shared/src/index.test.ts"));
  assert.ok(paths.includes("packages/ui/package.json"));
  assert.ok(paths.includes("packages/ui/tsconfig.json"));
  assert.ok(paths.includes("packages/ui/src/index.tsx"));
  assert.ok(paths.includes("packages/api/package.json"));
  assert.ok(paths.includes("packages/api/tsconfig.json"));
  assert.ok(paths.includes("packages/api/src/index.ts"));
  assert.ok(paths.includes("packages/api/src/index.test.ts"));
  assert.match(appTsConfig, /@tsuz\/shared/);
  assert.match(appTsConfig, /@tsuz\/ui/);
  assert.match(appTsConfig, /@tsuz\/api/);
  assert.match(appViteConfig, /@tsuz\/shared/);
  assert.match(appViteConfig, /@tsuz\/ui/);
  assert.match(appViteConfig, /@tsuz\/api/);
  assert.match(appViteConfig, /vite-plugin-qiankun/);
  assert.match(appViteConfig, /vitest\/config/);
  assert.match(appViteConfig, /environment: "jsdom"/);
  assert.match(appViteConfig, /setupFiles: "\.\/src\/test\/setup\.ts"/);
  assert.match(appViteConfig, /qiankun\("mfe-app"/);
  assert.match(appViteConfig, /dedupe: \["react", "react-dom"\]/);
  assert.match(main, /renderWithQiankun/);
  assert.match(main, /update/);
  assert.match(main, /qiankunWindow\.__POWERED_BY_QIANKUN__/);
  assert.match(bootstrap, /AppProviders/);
  assert.match(bootstrap, /useAppStore/);
  assert.match(bootstrap, /destroy\(\);/);
  assert.match(bootstrap, /createMfeApiClient/);
  assert.match(app, /BusinessHomePage/);
  assert.match(app, /@tsuz\/ui/);
  assert.match(businessHomePage, /useQuery/);
  assert.match(businessHomePage, /PageContainer/);
  assert.match(appProviders, /QueryClientProvider/);
  assert.match(appProviders, /BrowserRouter/);
  assert.match(queryClient, /new QueryClient/);
  assert.match(queryClient, /staleTime: 30_000/);
  assert.match(appStore, /create<AppStore>/);
  assert.match(appStore, /typeof window !== "undefined"/);
  assert.match(appStore, /setHostProps/);
  assert.match(appStore, /resetHostProps/);
  assert.match(businessHomeQuery, /businessHomeQueryKey/);
  assert.match(businessHomeQuery, /loadBusinessHomeSummary/);
  assert.match(files.find((file) => file.path === "playwright.config.ts")?.content ?? "", /127\.0\.0\.1:7201/);
  assert.match(files.find((file) => file.path === "e2e/standalone.spec.ts")?.content ?? "", /Standalone mode/);
  assert.match(files.find((file) => file.path === "apps/app/src/test/setup.ts")?.content ?? "", /@testing-library\/jest-dom/);
  assert.match(files.find((file) => file.path === "apps/app/src/pages/BusinessHomePage.test.tsx")?.content ?? "", /deterministic business data/);
  assert.match(qiankun, /@tsuz\/shared/);
  assert.match(qiankun, /Partial<MicroAppProps>/);
  assert.match(qiankun, /export async function bootstrap/);
  assert.match(qiankun, /export async function mount/);
  assert.match(qiankun, /render\(props\)/);
  assert.match(qiankun, /export async function unmount/);
  assert.match(qiankun, /destroy\(\)/);
  assert.match(qiankun, /export async function update/);
  assert.match(apiClient, /createApiClient/);
  assert.match(apiClient, /DEFAULT_API_BASE_URL/);
  assert.match(sharedSource, /export interface MicroAppProps/);
  assert.match(uiSource, /export function Logo/);
  assert.match(uiSource, /export function PageContainer/);
  assert.match(uiSource, /export function EmptyState/);
  assert.match(uiSource, /export function ErrorState/);
  assert.match(apiSource, /export function createApiClient/);
  assert.match(viteEnv, /VITE_API_BASE_URL/);
  assert.match(viteEnv, /VITE_MFE_APP_ENTRY/);
  assert.match(viteEnv, /VITE_APP_ENV/);
  assert.match(viteEnv, /__POWERED_BY_QIANKUN__/);
  assert.match(dockerfile, /FROM node:20-alpine AS build/);
  assert.match(dockerfile, /FROM nginx:1\.27-alpine/);
  assert.match(dockerfile, /ARG VITE_API_BASE_URL=\/api/);
  assert.match(dockerfile, /ARG VITE_MFE_APP_ENTRY=\/\/localhost:7201/);
  assert.match(dockerfile, /ARG VITE_APP_ENV=production/);
  assert.match(dockerfile, /COPY --from=build \/app\/apps\/app\/dist \/usr\/share\/nginx\/html/);
  assert.match(nginxConfig, /try_files \$uri \$uri\/ \/index\.html/);
  assert.match(nginxConfig, /Cache-Control "no-store, no-cache, must-revalidate"/);
  assert.match(nginxConfig, /Cache-Control "public, immutable"/);
  assert.match(nginxConfig, /Access-Control-Allow-Origin "\*"/);
  assert.match(nginxConfig, /Access-Control-Allow-Methods "GET, HEAD, OPTIONS"/);
  assert.match(compose, /\$\{DOCKER_IMAGE_NAME:-mfe-business\}:\$\{APP_VERSION:-local\}/);
  assert.match(compose, /\$\{CONTAINER_NAME:-mfe-business\}/);
  assert.match(compose, /"\$\{APP_PORT:-7201\}:80"/);
  assert.match(compose, /VITE_API_BASE_URL: \$\{VITE_API_BASE_URL:-\/api\}/);
  assert.match(compose, /VITE_MFE_APP_ENTRY: \$\{VITE_MFE_APP_ENTRY:-\/\/localhost:7201\}/);
  assert.match(compose, /VITE_APP_ENV: \$\{APP_ENV:-local\}/);
  assert.match(deployEnv, /DOCKER_IMAGE_NAME=mfe-business/);
  assert.match(deployEnv, /APP_VERSION=local/);
  assert.match(deployEnv, /APP_PORT=7201/);
  assert.match(deployEnv, /APP_ENV=local/);
  assert.match(deployEnv, /VITE_MFE_APP_ENTRY=\/\/localhost:7201/);
  assert.match(dockerignore, /apps\/\*\/dist/);
  assert.match(dockerignore, /!\.env\.deploy\.example/);
  assert.match(prettierConfig, /printWidth/);
  assertMfeCiWorkflow(workflow);
  assertMfeDeployWorkflow(deployWorkflow);
  assert.doesNotMatch(deployWorkflow, /:latest/);
  assert.match(appEnvExample, /VITE_APP_ENV=local/);
  assert.match(apiClient, /resolveDefaultApiBaseUrl/);
  assert.match(apiClient, /import\.meta\.env\.VITE_API_BASE_URL/);
  assert.match(readme, /Generated by Tsu from the `mfe-app` template/);
  assert.match(readme, /production-ready React qiankun sub application starter/);
  assert.match(readme, /Generate the Project/);
  assert.match(readme, /Local development/);
  assert.match(readme, /Local quality gates/);
  assert.match(readme, /tsu-cli init mfe-business-app --template mfe-app/);
  assert.match(readme, /GitHub Actions CI/);
  assert.match(readme, /GitHub Actions Deploy/);
  assert.match(readme, /GitHub Environments/);
  assert.match(readme, /test-v\*\.\*\.\*/);
  assert.match(readme, /product-v\*\.\*\.\*/);
  assert.match(readme, /test-v1\.0\.1/);
  assert.match(readme, /product-v1\.0\.1/);
  assert.match(readme, /workflow_dispatch/);
  assert.match(readme, /image_tag/);
  assert.match(readme, /rollback/);
  assert.match(readme, /docker compose up -d --no-build/);
  assert.match(readme, /deploy\.yml automatically uploads docker-compose\.yml/);
  assert.match(readme, /DOCKER_REGISTRY_TOKEN/);
  assert.match(readme, /SSH_PRIVATE_KEY/);
  assert.match(readme, /VITE_API_BASE_URL is a build-time variable/);
  assert.match(readme, /pnpm format:check/);
  assert.match(readme, /Testing Library/);
  assert.match(readme, /Playwright/);
  assert.match(readme, /Host Mode/);
  assert.match(readme, /apps\/app\/src\/pages\/BusinessHomePage\.tsx/);
  assert.match(readme, /pnpm test/);
  assert.match(readme, /pnpm test:e2e/);
  assert.match(readme, /standalone\.spec\.ts/);
  assert.match(readme, /\.github\/workflows\/ci\.yml/);
  assert.doesNotMatch(readme, /Phase 4 React qiankun sub application skeleton/);
});

test("template source files use project name token", () => {
  const sourceFiles = createTemplateSourceFiles("default");
  const packageJson = sourceFiles.find((file) => file.path === "package.json");

  assert.ok(packageJson);
  assert.match(packageJson.content, new RegExp(templateProjectNameToken));
  assert.match(renderTemplateFiles(sourceFiles, "My App")[0].content, /"name": "my-app"/);
});

test("createTemplateFiles rejects unknown templates", () => {
  assert.throws(
    () => createTemplateFiles({ projectName: "demo", templateName: "missing" }),
    /Available templates: default, monorepo, vue3, mfe, mfe-main, mfe-app, react, python-main, python-app/
  );
});
